apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gitlab-merge-request
  title: Create catalog-info for gitlab
  description: Scaffolder template to create catalog-info.yaml
spec:
  owner: user:denair
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description:  Name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        description:
          title: Description
          type: string
          description: Description of the component
        title:
          title: Title
          type: string
          description: Title of the component
        namespace:
          title: Namespace
          type: string
          description: Which namespace does the component belong to? e.g. - devex
        project:
          title: Jira Project Key
          type: string
          description: Project key for your Jira project. e.g. DEE, ONEPLAT, CPCORE, etc;
        targetPath:
          title: Target Path of the repo
          type: string
          description: Name of the directory to create in the repository
        branchName:
          title: Destination Branch Name
          type: string
          description: Name of the branch to create in the repository
        assignee:
          title: MR Assignee
          type: string
          description: GitLab Handle of the Assignee
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.com

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./template
        targetPath: ${{ parameters.targetPath }}
        values:
          name: ${{parameters.name}}
    - id: publish
      name: Publish
      action: publish:gitlab:merge-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: Creating catalog-info.yaml ${{ parameters.name }} for backstage
        branchName: ${{ parameters.branchName }}
        description: |
          # New project: ${{ parameters.name }}
          ${{ parameters.description if parameters.description }}
        targetPath: ${{ parameters.targetPath if parameters.targetPath else '.' }}
        commitAction: create
        removeSourceBranch: true
        assignee: ${{ parameters.assignee }}

  output:
    links: 
      - url: ${{ steps.publish.output.mergeRequestUrl }}
        title: 'Go to Gitlab MR'