apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: hello-world-mr
  title: Hello World MR template 
  description: create a Hello World catalog-info.yml
spec:
  owner: user:hybridx
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Provide Service information
      required:
        - service_name
      properties:
        service_name:
          title: Name
          type: string
          description: No special chars, numbers as the first char, or dashes as the first or last char. 
          ui:autofocus: true
    - title: Provide Repo URL
      required:
        - repo_url
      properties:
        repo_url:
          title: Repo URL
          type: string
          description: Add you repo_url
          ui:autofocus: true
  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetchTemplate
      name: Fetch diff
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.service_name }}

    - id: openMergeRequest
      name: Open merge request
      action: publish:gitlab:merge-request
      input:
        repoUrl: ${{parameters.repo_url}}
        branchName: backstage-app-dev-branch
        title: Make a change to state
        description: 'This is an automated PR'

  output:
    resp: ${{ steps.openMergeRequest.output.remoteUrl }}