apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: react-with-spaship-template
  title: React app with SPAship
  description: Create a new react website project for gitlab with basic CI/CD pipeline
  tags:
    - react
    - vite
    - spaship
    - gitlab
    - ci
    - template
spec:
  owner: hybridx
  type: website

  parameters:
    - title: Provide some simple information
      required:
        - spa_name
        - spa_path
      properties:
        spa_name:
          title: SPA Name
          type: string
          description: Please enter the SPA/Application name
          ui:field: EntityNamePicker
          ui:autofocus: true
        spa_path:
          title: Path Name
          type: string
          description: Please enter path without forward-slash ('/').
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this SPA/Application is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [Group, User]

    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.com
              - github.com
  steps:
    - id: fetch-base
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          spa_name: ${{ parameters.spa_name }}
          spa_path: ${{ parameters.spa_path }}
          description: ${{ parameters.description }}
          repoUrl: ${{ parameters.repoUrl }}
          owner: ${{ parameters.owner }}

    - id: fetch-gitlab-ci
      if: ${{ parameters.repoUrl | parseRepoUrl | pick('host') === 'gitlab.com' }}
      name: Fetch Gitlab-CI
      action: fetch:template
      input: 
        url: ./gitlab

    - id: fetch-github-action
      if: ${{ parameters.repoUrl | parseRepoUrl | pick('host') === 'github.com' }}
      name: Fetch Github Action
      action: fetch:template
      input: 
        url: ./github
      
    - id: publish
      if: ${{ parameters.repoUrl | parseRepoUrl | pick('host') === 'gitlab.com' }}
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts:
          - gitlab.com
        description: This is ${{ parameters.spa_name }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: public
    
    - id: publish
      if: ${{ parameters.repoUrl | parseRepoUrl | pick('host') === 'github.com' }}
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.spa_name }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }} 
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
